# Generated by Django 5.1.6 on 2025-07-25 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('model', models.CharField(max_length=100)),
                ('no_of_passengers', models.CharField(max_length=50)),
                ('load_kg', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.brand')),
                ('cabin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.cabin')),
                ('controller_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.controllerbrand')),
                ('door_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.doorbrand')),
                ('door_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.doortype')),
                ('floor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.floorid')),
                ('lift_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.lifttype')),
                ('machine_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.machinebrand')),
                ('machine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.machinetype')),
            ],
        ),
    ]
