# Generated by Django 5.1.6 on 2025-07-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('threshold_qty', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_type', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], default='Goods', max_length=10)),
                ('tax_preference', models.CharField(choices=[('Taxable', 'Taxable'), ('Non-Taxable', 'Non-Taxable')], default='Non-Taxable', max_length=15)),
                ('sac_code', models.CharField(blank=True, max_length=10, null=True)),
                ('hsn_hac_code', models.CharField(blank=True, max_length=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.make')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.type')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.unit')),
            ],
        ),
    ]
