# Generated by Django 5.1.6 on 2025-07-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_make_type_unit_item'),
        ('sales', '0002_customer_active_mobile_customer_completed_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=10, unique=True)),
                ('type', models.CharField(choices=[('Site Inspection', 'Site Inspection'), ('Spec Checking', 'Spec Checking'), ('Break Down Calls', 'Break Down Calls'), ('Service Request', 'Service Request'), ('New Installation', 'New Installation')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100)),
                ('contact_person_mobile', models.CharField(blank=True, max_length=15)),
                ('block_wing', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('customer_signature', models.TextField(blank=True)),
                ('technician_remark', models.TextField(blank=True)),
                ('technician_signature', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employee')),
            ],
        ),
    ]
