# Generated by Django 5.1.6 on 2025-10-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_lift_block_lift_license_end_date_lift_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
