# Generated by Django 5.1.6 on 2025-08-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hsn_hac_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase_price',
        ),
    ]
