# Generated by Django 5.1.6 on 2025-09-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='lift_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
