# Generated by Django 5.1.6 on 2025-07-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_customer_active_mobile_customer_completed_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('invoice_frequency', models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi Annually'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('every_other_weekly', 'Every Other Weekly')], default='annually', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='amc_uploads/')),
                ('equipment_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_generate_contract', models.BooleanField(default=False)),
                ('no_of_services', models.IntegerField(default=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.paymentterms')),
            ],
        ),
    ]
