# Generated by Django 5.1.6 on 2025-08-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('amcname', models.CharField(blank=True, max_length=100)),
                ('invoice_frequency', models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi Annually'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('every_other_weekly', 'Every Other Weekly')], default='annually', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('equipment_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_generate_contract', models.BooleanField(default=False)),
                ('no_of_services', models.IntegerField(default=12)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('no_of_lifts', models.IntegerField(default=0)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMCType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
