# Generated by Django 5.1.6 on 2025-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('amcname', models.CharField(blank=True, max_length=100)),
                ('invoice_frequency', models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi Annually'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('per_service', 'Per Service')], default='annually', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('equipment_no', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_generate_contract', models.BooleanField(default=False)),
                ('no_of_services', models.IntegerField(blank=True, default=12, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('no_of_lifts', models.IntegerField(blank=True, default=0, null=True)),
                ('gst_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMCType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
