# Generated by Django 5.1.6 on 2025-07-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='amc',
            name='no_of_lifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amc',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='amc',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
