# Generated by Django 5.1.6 on 2025-09-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
