# Generated by Django 5.1.6 on 2025-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='invoice_frequency',
            field=models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi Annually'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('per_service', 'Per Service')], default='annually', max_length=20),
        ),
        migrations.AlterField(
            model_name='amc',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
    ]
