# Generated by Django 5.1.6 on 2025-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_amc_gst_percentage_amc_no_of_lifts_amc_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
