# Generated by Django 5.1.6 on 2025-08-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_amc_status'),
        ('authentication', '0003_employee_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='amc_service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.item'),
        ),
    ]
