# Generated by Django 5.1.6 on 2025-09-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_alter_amc_invoice_frequency_alter_amc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='equipment_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='no_of_lifts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='no_of_services',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='total_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
