# Generated by Django 5.1.6 on 2025-08-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_amc_amc_service_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amc',
            name='uploads_files',
        ),
    ]
