# Generated by Django 5.1.6 on 2025-08-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_remove_amc_uploads_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='amc_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
