# Generated by Django 5.1.6 on 2025-08-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0006_amc_amc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='amc',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='amc',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
