# Generated by Django 5.1.6 on 2025-08-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0007_amc_amount_due_amc_contract_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
