# Generated by Django 5.1.6 on 2025-08-18 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amc', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('site_id', models.CharField(max_length=30)),
                ('job_no', models.CharField(blank=True, max_length=50)),
                ('site_name', models.CharField(max_length=100)),
                ('site_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('office_address', models.TextField(blank=True)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='private', max_length=20)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('active_mobile', models.IntegerField(default=0)),
                ('expired_mobile', models.IntegerField(default=0)),
                ('contracts', models.IntegerField(default=0)),
                ('no_of_lifts', models.IntegerField(default=0)),
                ('completed_services', models.IntegerField(default=0)),
                ('due_services', models.IntegerField(default=0)),
                ('overdue_services', models.IntegerField(default=0)),
                ('tickets', models.IntegerField(default=0)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='customer_uploads/')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.branch')),
                ('province_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.provincestate')),
                ('routes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.route')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_term', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT')], default='cash', max_length=10)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='invoice_uploads/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='open', max_length=20)),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('type', models.CharField(choices=[('Parts/Peripheral Quotation', 'Parts/Peripheral Quotation'), ('Repair', 'Repair'), ('AMC Renewal Quotation', 'AMC Renewal Quotation'), ('AMC', 'AMC')], default='Parts/Peripheral Quotation', max_length=50)),
                ('year_of_make', models.CharField(blank=True, max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('other_remark', models.TextField(blank=True)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='quotation_uploads/')),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('lifts', models.ManyToManyField(to='authentication.lift')),
                ('sales_service_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employee')),
            ],
        ),
    ]
