# Generated by Django 5.1.6 on 2025-09-25 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amc', '0001_initial'),
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('site_id', models.CharField(max_length=30)),
                ('job_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('site_name', models.CharField(max_length=100)),
                ('site_address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('office_address', models.TextField(blank=True)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private')], default='private', max_length=20, null=True)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('active_mobile', models.IntegerField(default=0)),
                ('expired_mobile', models.IntegerField(default=0)),
                ('contracts', models.IntegerField(default=0)),
                ('no_of_lifts', models.IntegerField(default=0)),
                ('completed_services', models.IntegerField(default=0)),
                ('due_services', models.IntegerField(default=0)),
                ('overdue_services', models.IntegerField(default=0)),
                ('tickets', models.IntegerField(default=0)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='customer_uploads/')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.branch')),
                ('lifts', models.ManyToManyField(blank=True, to='authentication.lift')),
                ('province_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.provincestate')),
                ('routes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.route')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='license_attachments/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='sales.customer')),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lift')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_term', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT')], default='cash', max_length=10)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='invoice_uploads/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='open', max_length=20)),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.item')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('tax_deducted', models.CharField(choices=[('no', 'No Tax deducted'), ('yes_tds', 'Yes, TDS (Income Tax)')], default='no', max_length=20)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='payment_received_uploads/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('type', models.CharField(choices=[('Parts/Peripheral Quotation', 'Parts/Peripheral Quotation'), ('Repair', 'Repair'), ('AMC Renewal Quotation', 'AMC Renewal Quotation'), ('AMC', 'AMC')], default='Parts/Peripheral Quotation', max_length=50)),
                ('year_of_make', models.CharField(blank=True, max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('other_remark', models.TextField(blank=True)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='quotation_uploads/')),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('lifts', models.ManyToManyField(to='authentication.lift')),
                ('sales_service_executive', models.ForeignKey(blank=True, limit_choices_to={'role': 'SALESMAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('repeat_every', models.CharField(choices=[('week', 'Week'), ('2week', '2 Weeks'), ('month', 'Month'), ('2month', '2 Months'), ('3month', '3 Months'), ('6month', '6 Months'), ('year', 'Year'), ('2year', '2 Years')], default='month', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True)),
                ('gst_treatment', models.CharField(blank=True, max_length=50)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='recurring_invoice_uploads/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('sales_person', models.ForeignKey(blank=True, limit_choices_to={'role': 'SALESMAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.item')),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.recurringinvoice')),
            ],
        ),
    ]
