# Generated by Django 5.1.6 on 2025-08-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('repeat_every', models.CharField(choices=[('week', 'Week'), ('2week', '2 Weeks'), ('month', 'Month'), ('2month', '2 Months'), ('3month', '3 Months'), ('6month', '6 Months'), ('year', 'Year'), ('2year', '2 Years')], default='week', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True)),
                ('gst_treatment', models.CharField(blank=True, max_length=50)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='recurring_invoice_uploads/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.item')),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.recurringinvoice')),
            ],
        ),
    ]
