# Generated by Django 5.1.6 on 2025-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='completed_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='contracts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='due_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='expired_mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_lifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='overdue_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_id',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
