# Generated by Django 5.1.6 on 2025-08-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_recurringinvoice_recurringinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
