# Generated by Django 5.1.6 on 2025-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customerlicense_lift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlicense',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerlicense',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
