# Generated by Django 5.1.6 on 2025-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sector',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private')], default='private', max_length=20, null=True),
        ),
    ]
