# Generated by Django 5.1.6 on 2025-07-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_active_mobile_customer_completed_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_sms_notification',
        ),
    ]
