# Generated by Django 5.1.6 on 2025-08-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_recurringinvoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('tax_deducted', models.CharField(choices=[('no', 'No Tax deducted'), ('yes_tds', 'Yes, TDS (Income Tax)')], default='no', max_length=20)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='payment_received_uploads/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice')),
            ],
        ),
    ]
