# Generated by Django 5.1.6 on 2025-07-29 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_amc_status'),
        ('authentication', '0003_employee_complaint'),
        ('sales', '0003_remove_customer_mobile_sms_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('type', models.CharField(choices=[('Parts/Peripheral Quotation', 'Parts/Peripheral Quotation'), ('Repair', 'Repair'), ('AMC Renewal Quotation', 'AMC Renewal Quotation'), ('AMC', 'AMC')], default='Parts/Peripheral Quotation', max_length=50)),
                ('year_of_make', models.CharField(blank=True, max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('other_remark', models.TextField(blank=True)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='quotation_uploads/')),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
                ('lifts', models.ManyToManyField(to='authentication.lift')),
                ('sales_service_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employee')),
            ],
        ),
    ]
