# Generated by Django 5.1.6 on 2025-07-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_amc_status'),
        ('sales', '0004_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_term', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT')], default='cash', max_length=10)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='invoice_uploads/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='open', max_length=20)),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
            ],
        ),
    ]
