# Generated by Django 5.1.6 on 2025-08-25 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile'),
        ('sales', '0004_paymentreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoice',
            name='last_generated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='repeat_every',
            field=models.CharField(choices=[('week', 'Week'), ('2week', '2 Weeks'), ('month', 'Month'), ('2month', '2 Months'), ('3month', '3 Months'), ('6month', '6 Months'), ('year', 'Year'), ('2year', '2 Years')], default='month', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.item')),
            ],
        ),
    ]
