# Generated by Django 5.1.6 on 2025-09-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile'),
        ('sales', '0005_recurringinvoice_last_generated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lifts',
            field=models.ManyToManyField(blank=True, to='authentication.lift'),
        ),
    ]
