# Generated by Django 5.1.6 on 2025-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='site_id',
            field=models.CharField(max_length=30),
        ),
    ]
