# Generated by Django 5.1.6 on 2025-09-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile'),
        ('sales', '0006_customer_lifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='license_attachments/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='sales.customer')),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lift')),
            ],
        ),
    ]
