# Generated by Django 5.1.6 on 2025-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_customer_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uploads_files',
            field=models.FileField(blank=True, null=True, upload_to='customer_uploads/'),
        ),
    ]
